[[language]]
name = "markdown"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "toml"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "nix"
indent = { tab-width = 2, unit = "  " }
